language: generic

env:
  global:
    - PYMODULE: leave
    - RELEASE_PYTHON_VERSIONS: "3.5 3.6"
    - TWINE_USERNAME: dontcare
    - TWINE_REPOSITORY: leave
    - TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    - CIBW_SKIP="cp26-* cp27-* cp33-* cp34*"
    - CIBW_OUPUT_DIR="dist/"

matrix:
  fast_finish: true
  include:
    #- os: osx
    #  services: [docker]
    #  env:
    #    - CIBW_BEFORE_BUILD="sh -c 'pip install cython && make all'"
    #    - PLATFORM=macos
    #  
    - os: linux
      dist: trusty
      branches: {only: [master]}
      sudo: required
      language: python
      python: "3.5"
      services: [docker]
      env: BUILD=tests,wheels,release
      install:
        - pip install --upgrade pip
        - make

cache:
  pip
